// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppCapabilities = { profileStorage: boolean, secureCredentials: boolean, ssh: boolean, terminal: boolean, sftp: boolean, monitor: boolean, };
