// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorAction } from "./ErrorAction";
import type { ErrorCode } from "./ErrorCode";

/**
 * Safe error payload crossing the IPC boundary.
 */
export type AppError = { code: ErrorCode, messageKey: string, params: { [key in string]: string }, retryable: boolean, action: ErrorAction, stage: string | null, requestId: string | null, details: string | null, };
