// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppCapabilities } from "./AppCapabilities";

export type AppInfo = { name: string, version: string, apiVersion: number, platform: string, architecture: string, capabilities: AppCapabilities, };
