// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorStyle } from "./CursorStyle";
import type { Language } from "./Language";
import type { Theme } from "./Theme";

export type AppSettings = { theme: Theme, language: Language, terminalFontFamily: string, terminalFontSize: number, terminalCursorStyle: CursorStyle, terminalScrollbackLines: number, downloadDirectoryToken: string | null, confirmBeforeDisconnect: boolean, };
