// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { AppIconStyle } from "./AppIconStyle";
import type { CursorStyle } from "./CursorStyle";
import type { Language } from "./Language";
import type { TerminalBackgroundImageSettings } from "./TerminalBackgroundImageSettings";
import type { TerminalCustomColors } from "./TerminalCustomColors";
import type { TerminalThemeMode } from "./TerminalThemeMode";
import type { Theme } from "./Theme";

export type AppSettings = { theme: Theme, appIconStyle: AppIconStyle, accentColor: AccentColor, customAccentColor: string | null, language: Language, terminalFontFamily: string, terminalFontSize: number, terminalCursorStyle: CursorStyle, terminalScrollbackLines: number, terminalThemeMode: TerminalThemeMode, terminalCustomColors: TerminalCustomColors, terminalBackgroundImage: TerminalBackgroundImageSettings, terminalLineHeight: number, terminalCursorBlink: boolean, downloadDirectoryToken: string | null, confirmBeforeDisconnect: boolean, showSizeColumn: boolean, showFileSizes: boolean, showFolderSizes: boolean, };
