// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialKind } from "./CredentialKind";

export type AuthenticationChallenge = { challengeId: string, connectionId: string, credentialKind: CredentialKind, expiresAtMs: number, };
