// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundImageAsset = { id: string, fileName: string, mediaType: string, width: number, height: number, byteLength: number, createdAtMs: number, };
