// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Secret } from "./Secret";
import type { ServerProfileDraft } from "./ServerProfileDraft";

export type ConnectionStartSource = { "kind": "saved", serverId: string, expectedRevision: number, } | { "kind": "draft", profile: ServerProfileDraft, credential: Secret | null, };
