// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionMode } from "./ConnectionMode";
import type { ConnectionStartSource } from "./ConnectionStartSource";

export type ConnectionStartPayload = { source: ConnectionStartSource, mode: ConnectionMode, };
