// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionPreflightError } from "./ConnectionPreflightError";

export type ConnectionPreflightResult = { resolvedAddresses: Array<string>, selectedAddress: string | null, dnsDurationMs: number, tcpReachable: boolean | null, tcpConnectDurationMs: number | null, error: ConnectionPreflightError | null, checkedAtMs: number, };
