// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { AuthenticationChallenge } from "./AuthenticationChallenge";
import type { ConnectionMode } from "./ConnectionMode";
import type { ConnectionState } from "./ConnectionState";
import type { HostKeyChallenge } from "./HostKeyChallenge";
import type { NegotiatedAlgorithms } from "./NegotiatedAlgorithms";

export type ConnectionSnapshot = { connectionId: string, serverId: string | null, mode: ConnectionMode, state: ConnectionState, hostKeyChallenge: HostKeyChallenge | null, authenticationChallenge: AuthenticationChallenge | null, negotiatedAlgorithms: NegotiatedAlgorithms | null, error: AppError | null, createdAtMs: number, updatedAtMs: number, };
