// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevealMode } from "./RevealMode";

export type CredentialRevealPolicy = { mode: RevealMode, revision: number, hasSecondaryPassword: boolean, nativeAuthAvailable: boolean, nativeAuthReason: string | null, lockedUntilMs: number | null, };
