// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Secret } from "./Secret";

export type CredentialRevealTarget = { serverId: string, secondaryPassword: Secret | null, };
