// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JSON-safe wire representation for counters and byte sizes that may exceed
 * JavaScript's exact integer range.
 */
export type DecimalU64 = string;
