// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoIpDatabaseInfo } from "./GeoIpDatabaseInfo";

export type GeoIpDatabaseStatus = { location: GeoIpDatabaseInfo | null, asn: GeoIpDatabaseInfo | null, automaticUpdates: boolean, updateIntervalDays: number, lastCheckedAtMs: number | null, lastError: string | null, };
