// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupUpdate } from "./GroupUpdate";

export type GroupUpdatePayload = { groupId: string, update: GroupUpdate, };
