// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostKeyRecord = { normalizedHost: string, port: number, algorithm: string, fingerprintSha256: string, revision: number, trustedAtMs: number, };
