// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostKeyDecision } from "./HostKeyDecision";

export type HostKeyRespondPayload = { connectionId: string, challengeId: string, decision: HostKeyDecision, };
