// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalU64 } from "./DecimalU64";

export type MonitorNetworkInterface = { name: string, receivedBytes: DecimalU64, transmittedBytes: DecimalU64, receivedBytesPerSecond: number | null, transmittedBytesPerSecond: number | null, };
