// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorMetricQuality } from "./MonitorMetricQuality";

export type MonitorSystemSnapshot = { hostname: string | null, os: string | null, kernel: string | null, architecture: string | null, quality: MonitorMetricQuality, };
