// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorHistoryMetric } from "./MonitorHistoryMetric";

export type MonitorGetHistoryPayload = { connectionId: string, metric: MonitorHistoryMetric, fromMs: number | null, toMs: number | null, limit: number | null, };
