// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MonitorHistoryMetric = "cpuUsage" | "memoryUsage" | "diskUsage" | "networkReceiveRate" | "networkTransmitRate" | "loadOneMinute";
