// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorMetricQuality } from "./MonitorMetricQuality";
import type { MonitorNetworkInterface } from "./MonitorNetworkInterface";

export type MonitorNetworkSnapshot = { receivedBytesPerSecond: number | null, transmittedBytesPerSecond: number | null, interfaces: Array<MonitorNetworkInterface>, quality: MonitorMetricQuality, };
