// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorHistoryMetric } from "./MonitorHistoryMetric";
import type { MonitorHistorySample } from "./MonitorHistorySample";

export type MonitorHistoryPage = { connectionId: string, metric: MonitorHistoryMetric, samples: Array<MonitorHistorySample>, };
