// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorMetricQuality } from "./MonitorMetricQuality";

export type MonitorLoadSnapshot = { oneMinute: number | null, fiveMinutes: number | null, fifteenMinutes: number | null, quality: MonitorMetricQuality, };
