// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorQualityStatus } from "./MonitorQualityStatus";

export type MonitorMetricQuality = { status: MonitorQualityStatus, sampledAtMs: number | null, collectionDurationMs: number | null, errorCode: string | null, };
