// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalU64 } from "./DecimalU64";
import type { MonitorMetricQuality } from "./MonitorMetricQuality";

export type MonitorUptimeSnapshot = { seconds: DecimalU64 | null, quality: MonitorMetricQuality, };
