// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorMetricQuality } from "./MonitorMetricQuality";

export type MonitorCpuSnapshot = { usagePercent: number | null, logicalCores: number | null, quality: MonitorMetricQuality, };
