// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorCpuSnapshot } from "./MonitorCpuSnapshot";
import type { MonitorDiskSnapshot } from "./MonitorDiskSnapshot";
import type { MonitorLoadSnapshot } from "./MonitorLoadSnapshot";
import type { MonitorMemorySnapshot } from "./MonitorMemorySnapshot";
import type { MonitorNetworkSnapshot } from "./MonitorNetworkSnapshot";
import type { MonitorSystemSnapshot } from "./MonitorSystemSnapshot";
import type { MonitorUptimeSnapshot } from "./MonitorUptimeSnapshot";

export type MonitorSnapshot = { connectionId: string, cpu: MonitorCpuSnapshot, load: MonitorLoadSnapshot, memory: MonitorMemorySnapshot, disk: MonitorDiskSnapshot, network: MonitorNetworkSnapshot, uptime: MonitorUptimeSnapshot, system: MonitorSystemSnapshot, };
