// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalU64 } from "./DecimalU64";
import type { MonitorMetricQuality } from "./MonitorMetricQuality";

export type MonitorDiskSnapshot = { usedBytes: DecimalU64 | null, totalBytes: DecimalU64 | null, availableBytes: DecimalU64 | null, usedPercent: number | null, source: string | null, mount: string | null, quality: MonitorMetricQuality, };
