// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NegotiatedAlgorithms = { keyExchange: string, hostKey: string, cipher: string, clientMac: string, serverMac: string, clientCompression: string, serverCompression: string, };
