// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoIpDatabaseSource } from "./GeoIpDatabaseSource";
import type { NetworkGeo } from "./NetworkGeo";
import type { NetworkHostKind } from "./NetworkHostKind";
import type { NetworkInspectionSource } from "./NetworkInspectionSource";
import type { NetworkIpVersion } from "./NetworkIpVersion";
import type { NetworkScope } from "./NetworkScope";

export type NetworkInspection = { inputHost: string, hostKind: NetworkHostKind, resolvedAddresses: Array<string>, primaryAddress: string | null, ipVersion: NetworkIpVersion | null, scope: NetworkScope | null, reverseDns: string | null, geo: NetworkGeo, asn: string | null, organization: string | null, source: NetworkInspectionSource, databaseUpdatedAtMs: number | null, databaseSource: GeoIpDatabaseSource | null, };
