// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkGeo = { countryCode: string | null, countryName: string | null, region: string | null, city: string | null, };
