// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalU64 } from "./DecimalU64";
import type { RemoteFileType } from "./RemoteFileType";

export type RemoteFileEntry = { name: string, path: string, fileType: RemoteFileType, sizeBytes: DecimalU64 | null, modifiedAtMs: number | null, isSymlink: boolean, permissions: number | null, };
