// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialKind } from "./CredentialKind";

export type RetainedCredential = { credentialRefId: string, ownerServerId: string, kind: CredentialKind, createdAtMs: number, updatedAtMs: number, };
