// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerEnvironment } from "./ServerEnvironment";
import type { TerminalAppearanceSettings } from "./TerminalAppearanceSettings";

export type ServerAppearance = { serverId: string, labelColor: string | null, environment: ServerEnvironment | null, terminalOverrideEnabled: boolean, terminalAppearance: TerminalAppearanceSettings, revision: number, updatedAtMs: number, };
