// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

export type ServerProfile = { id: string, name: string, host: string, port: number, username: string, authType: AuthType, hasPrivateKey: boolean, groupId: string | null, hasSavedCredential: boolean, connectTimeoutMs: number, keepaliveIntervalSeconds: number, revision: number, createdAtMs: number, updatedAtMs: number, };
