// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CredentialUpdate } from "./CredentialUpdate";
import type { ServerProfileDraft } from "./ServerProfileDraft";

export type ServerUpdatePayload = { serverId: string, expectedRevision: number, profile: ServerProfileDraft, credential: CredentialUpdate, };
