// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerProfile } from "./ServerProfile";

export type ServerListPage = { items: Array<ServerProfile>, nextCursor: string | null, };
