// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";
import type { ProxyType } from "./ProxyType";

export type ServerProfile = { id: string, name: string, host: string, port: number, username: string, authType: AuthType, hasPrivateKey: boolean, groupId: string | null, hasSavedCredential: boolean, connectTimeoutMs: number, keepaliveIntervalSeconds: number, jumpHost: string | null, jumpPort: number, proxyType: ProxyType | null, proxyHost: string | null, proxyPort: number | null, revision: number, createdAtMs: number, updatedAtMs: number, };
