// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

export type ServerProfileDraft = { name: string | null, host: string, port: number, username: string, authType: AuthType, privateKeyToken: string | null, groupId: string | null, connectTimeoutMs: number, keepaliveIntervalSeconds: number, };
