// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerListQuery = { query: string | null, groupId: string | null, limit: number, cursor: string | null, };
