// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings } from "./AppSettings";

export type SettingsRecord = { value: AppSettings, revision: number, updatedAtMs: number | null, };
