// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpUploadPayload = { connectionId: string, localFileToken: string, remotePath: string, };
