// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { DecimalU64 } from "./DecimalU64";
import type { SftpTransferDirection } from "./SftpTransferDirection";
import type { SftpTransferState } from "./SftpTransferState";

export type SftpTransferSnapshot = { transferId: string, connectionId: string, direction: SftpTransferDirection, fileName: string, finalPath: string, totalBytes: DecimalU64 | null, transferredBytes: DecimalU64, bytesPerSecond: number | null, remainingSeconds: bigint | null, state: SftpTransferState, error: AppError | null, cleanupRequired: boolean, temporaryPath: string | null, };
