// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpListStartPayload = { connectionId: string, 
/**
 * Remote POSIX path. Empty paths are treated as `.`.
 */
path: string, };
