// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteFileEntry } from "./RemoteFileEntry";

export type SftpDirectoryPage = { path: string, entries: Array<RemoteFileEntry>, cursorId: string | null, };
