// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpWriteTextPayload = { connectionId: string, path: string, content: string, expectedRevision: string, };
