// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteFileType } from "./RemoteFileType";

export type SftpDeletePayload = { connectionId: string, path: string, expectedType: RemoteFileType, confirmed: boolean, };
