// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecimalU64 } from "./DecimalU64";

export type TerminalWritePayload = { terminalId: string, inputSeq: DecimalU64, dataBase64: string, };
