// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalBackgroundFit } from "./TerminalBackgroundFit";
import type { TerminalBackgroundOverlayKind } from "./TerminalBackgroundOverlayKind";
import type { TerminalBackgroundPosition } from "./TerminalBackgroundPosition";

export type TerminalBackgroundImageSettings = { imageId: string | null, fit: TerminalBackgroundFit, position: TerminalBackgroundPosition, imageOpacity: number, overlayKind: TerminalBackgroundOverlayKind, overlayOpacity: number, blurPx: number, };
