// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { TerminalSize } from "./TerminalSize";
import type { TerminalState } from "./TerminalState";

export type TerminalSnapshot = { terminalId: string, connectionId: string, streamId: string, state: TerminalState, size: TerminalSize, exitStatus: number | null, exitSignal: string | null, error: AppError | null, createdAtMs: number, updatedAtMs: number, };
