// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalCustomColors = { background: string, foreground: string, cursor: string, selection: string, };
