// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalOpenPayload = { connectionId: string, columns: number, rows: number, pixelWidth: number | null, pixelHeight: number | null, };
