// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalBackgroundImageSettings } from "./TerminalBackgroundImageSettings";
import type { TerminalCustomColors } from "./TerminalCustomColors";
import type { TerminalThemeMode } from "./TerminalThemeMode";

export type TerminalAppearanceSettings = { themeMode: TerminalThemeMode, customColors: TerminalCustomColors, backgroundImage: TerminalBackgroundImageSettings, };
