export const settingsMessages = {
  done: ['完成', 'Done'],
  network: ['网络', 'Network'],
  settings: ['设置', 'Settings'], sections: ['设置分类', 'Settings sections'], general: ['通用', 'General'], appearance: ['外观', 'Appearance'], files: ['文件', 'Files'], terminal: ['终端', 'Terminal'], language: ['语言', 'Language'],
  showSizeColumn: ['显示大小列', 'Show size column'], showFileSizes: ['显示文件大小', 'Show file sizes'], showFolderSizes: ['显示文件夹大小', 'Show folder sizes'], folderSizeNote: ['按需递归统计目录中的文件大小，目录较大时需要一些时间；遇到无法读取的子目录时显示 —。', 'Folder sizes are calculated on demand by scanning files recursively. Large folders may take time; folders with unreadable descendants show —.'],
  confirmDisconnect: ['断开连接前确认', 'Confirm before disconnecting'], transferConfirmation: ['正在运行的传输仍需单独确认后才能取消。', 'Running transfers always require a separate confirmation before cancellation.'],
  theme: ['主题', 'Theme'], system: ['跟随系统', 'System'], light: ['浅色', 'Light'], dark: ['深色', 'Dark'], themeNote: ['保存后生效；系统主题随操作系统外观变化。', 'Applied on save. System theme follows operating system appearance.'], uiDensity: ['界面密度', 'UI density'], densityStandard: ['标准', 'Standard'], densityCompact: ['紧凑', 'Compact'], sidebarWidth: ['侧边栏宽度', 'Sidebar width'], sidebarNarrow: ['窄', 'Narrow'], sidebarStandard: ['标准', 'Standard'], sidebarWide: ['宽', 'Wide'], languageNote: ['保存后更新界面语言。服务器名称与远程内容保持原样。', 'Applied on save. Server names and remote content remain unchanged.'],
  accentColor: ['主题色', 'Accent color'], accentBlue: ['蓝色', 'Blue'], accentIndigo: ['靛青', 'Indigo'], accentPurple: ['紫色', 'Purple'], accentGreen: ['绿色', 'Green'], accentOrange: ['橙色', 'Orange'], accentRed: ['红色', 'Red'], accentCustom: ['自定义', 'Custom'], customAccentColor: ['自定义颜色', 'Custom color'], accentColorNote: ['主题色用于按钮、链接和焦点提示等强调元素；保存后生效。', 'The accent color is used for buttons, links and focus indicators. Applied on save.'],
  appIconStyle: ['应用图标样式', 'App icon style'], appIconPreview: ['应用图标预览', 'App icon preview'], appIconNote: ['保存后更新运行中的图标，重启后保留选择；macOS Finder 图标固定为浅色圆角。', 'Updates the running app icon on save and restores it on restart. The macOS Finder icon stays Light with rounded corners.'],
  terminalSettings: ['终端设置', 'Terminal settings'], terminalNote: ['字体、光标与滚动缓冲保存到 Rust SettingsService，并应用到活动终端。', 'Font, cursor and scrollback are saved by Rust SettingsService and applied to active terminals.'], reload: ['重新加载设置（放弃修改）', 'Reload settings (discard changes)'], cancel: ['取消', 'Cancel'], save: ['保存设置', 'Save settings'], saved: ['设置已保存。', 'Settings saved.'],
} as const;
